def show_menu():
    print("=" * 40)
    print("📚 Library Management System".center(40))
    print("=" * 40)
    print("\n1. ➕ Add Book")
    print("2. ➖ Remove Book")
    print("3. 📖 Borrow Book")
    print("4. ↩️  Return Book")
    print("5. 📚 Show Books")
    print("6. 🚪 Exit\n")
    print("=" * 40)
